# Course 601: Introduction to Data Science
## Course Project Topic: Weather Forecast


## Members:

   ## - Professor: Huthaifa Ashqar
   ## - Students:
<ul>
    <li>Sarang Rajendra Patil</li>
    <li>Aishwarya Kale</li>
    <li>Spandana Chennamaneni</li>
    <li>Sai Karteek Edumudi</li>
    <li>Suvidha Vaddula</li>
    <li>Levan Sulimanov</li>
</ul>
_________________________________________________________________________________

### Project Task List

- [x] Find Weather Dataset (KBWI airport, Maryland): https://www.ncdc.noaa.gov/cdo-web/datatools/lcd - **Levan**
- [x] Merge Datasets - **Karteek**
- [x] Fix Dataset column's data types using Excel - **Levan** 
- [x] Remove unnecessary columns and clean data type mixes in columns (two data types per column -> fix to single data type for consistency) - **Levan**
- [ ] NaN values interpolation - 
- [ ] Visualize weather dataset ( feature insights, etc.) - (2 graphs from each member)
    - [ ] **Sarang**
    - [ ] **Aishwarya**
    - [ ] **Spandana**
    - [ ] **Karteek**
    - [ ] **Suvidha**
    - [ ] **Levan**
- [ ] Visualization of correlation between features - **Sarang**  
- [ ] Data Distribution - **Spandana, Suvidha, Aishwarya**
- [ ] Correlate current data with POWER.LARC NASA's dataset (https://power.larc.nasa.gov/data-access-viewer/) - **Levan**
- [ ] Split data for train, test, validate (7 days to predict next 7 days - needs group discussion)
- [ ] Train Data using Logistic Regression
- [ ] Evaluate LogReg model (precision, recall, etc)
- [ ] Train Data using Random Forest
- [ ] Evaluate RFR model (precision, recall, etc)
- [ ] Train Data using RNN
- [ ] Evaluate RFR model (precision, recall, etc)
- [ ] **Paper**
    - [ ] Abstract - **Aishwarya**
    - [ ] Introduction - 
    - [ ] Previous Approaches
    - [ ] Our changes/approach (description of each approach)
    - [ ] Results
    - [ ] Plots

# Project implementation:

### Module Imports

In [5]:
import os
import pandas as pd

### Steps to merge the data and set column data types (dtypes)

In [18]:
# We provide merged file at the end, so this section is commented out

# Import initial data and check imported data

# # get current directory
# curr_dir = os.getcwd()

# data_dir = os.path.join(curr_dir, "main_data")

# # dataset name
# data1 = "1991_2000.csv"
# data2 = "2001_2010.csv"
# data3 = "2011_2020.csv"

# df1_dir = os.path.join(data_dir, data1)
# df2_dir = os.path.join(data_dir, data2)
# df3_dir = os.path.join(data_dir, data3)

# df1 = pd.read_csv(df1_dir) # dtype={0:str, 1:str, 2:str, 3:str, 4:int, })
# df2 = pd.read_csv(df2_dir)
# df3 = pd.read_csv(df3_dir)

# df_parts = [df1, df2, df3]
# merged_data = pd.concat(df_parts)

In [4]:
# merged_data.head(5)

##### We see that a lot of values are labeled as NaN
##### We have found that this happens due to unknown data type per column, and this can be fixed using manual set of dtype per column

##### In the Excel, each column was investigated and assigned appropriate data type: integer, float (2 decimal), text

In [ ]:
# Following is the list of column names from merged csv

In [ ]:
'''
['STATION':str,
 'DATE':str,
 'REPORT_TYPE':str,
 'SOURCE':str,
 'AWND',
 'BackupDirection',
 'BackupDistance',
 'BackupDistanceUnit',
 'BackupElements',
 'BackupElevation',
 'BackupElevationUnit',
 'BackupEquipment',
 'BackupLatitude',
 'BackupLongitude',
 'BackupName',
 'CDSD',
 'CLDD',
 'DSNW',
 'DailyAverageDewPointTemperature',
 'DailyAverageDryBulbTemperature',
 'DailyAverageRelativeHumidity',
 'DailyAverageSeaLevelPressure',
 'DailyAverageStationPressure',
 'DailyAverageWetBulbTemperature',
 'DailyAverageWindSpeed',
 'DailyCoolingDegreeDays',
 'DailyDepartureFromNormalAverageTemperature',
 'DailyHeatingDegreeDays',
 'DailyMaximumDryBulbTemperature',
 'DailyMinimumDryBulbTemperature',
 'DailyPeakWindDirection',
 'DailyPeakWindSpeed',
 'DailyPrecipitation',
 'DailySnowDepth',
 'DailySnowfall',
 'DailySustainedWindDirection',
 'DailySustainedWindSpeed',
 'DailyWeather',
 'HDSD',
 'HTDD',
 'HeavyFog',
 'HourlyAltimeterSetting',
 'HourlyDewPointTemperature',
 'HourlyDryBulbTemperature',
 'HourlyPrecipitation',
 'HourlyPresentWeatherType',
 'HourlyPressureChange',
 'HourlyPressureTendency',
 'HourlyRelativeHumidity',
 'HourlySeaLevelPressure',
 'HourlySkyConditions',
 'HourlyStationPressure',
 'HourlyVisibility',
 'HourlyWetBulbTemperature',
 'HourlyWindDirection',
 'HourlyWindGustSpeed',
 'HourlyWindSpeed',
 'MonthlyAverageRH',
 'MonthlyDaysWithGT001Precip',
 'MonthlyDaysWithGT010Precip',
 'MonthlyDaysWithGT32Temp',
 'MonthlyDaysWithGT90Temp',
 'MonthlyDaysWithLT0Temp',
 'MonthlyDaysWithLT32Temp',
 'MonthlyDepartureFromNormalAverageTemperature',
 'MonthlyDepartureFromNormalCoolingDegreeDays',
 'MonthlyDepartureFromNormalHeatingDegreeDays',
 'MonthlyDepartureFromNormalMaximumTemperature',
 'MonthlyDepartureFromNormalMinimumTemperature',
 'MonthlyDepartureFromNormalPrecipitation',
 'MonthlyDewpointTemperature',
 'MonthlyGreatestPrecip',
 'MonthlyGreatestPrecipDate',
 'MonthlyGreatestSnowDepth',
 'MonthlyGreatestSnowDepthDate',
 'MonthlyGreatestSnowfall',
 'MonthlyGreatestSnowfallDate',
 'MonthlyMaxSeaLevelPressureValue',
 'MonthlyMaxSeaLevelPressureValueDate',
 'MonthlyMaxSeaLevelPressureValueTime',
 'MonthlyMaximumTemperature',
 'MonthlyMeanTemperature',
 'MonthlyMinSeaLevelPressureValue',
 'MonthlyMinSeaLevelPressureValueDate',
 'MonthlyMinSeaLevelPressureValueTime',
 'MonthlyMinimumTemperature',
 'MonthlySeaLevelPressure',
 'MonthlyStationPressure',
 'MonthlyTotalLiquidPrecipitation',
 'MonthlyTotalSnowfall',
 'MonthlyWetBulb',
 'NormalsCoolingDegreeDay',
 'NormalsHeatingDegreeDay',
 'REM',
 'REPORT_TYPE.1',
 'SOURCE.1',
 'ShortDurationEndDate005',
 'ShortDurationEndDate010',
 'ShortDurationEndDate015',
 'ShortDurationEndDate020',
 'ShortDurationEndDate030',
 'ShortDurationEndDate045',
 'ShortDurationEndDate060',
 'ShortDurationEndDate080',
 'ShortDurationEndDate100',
 'ShortDurationEndDate120',
 'ShortDurationEndDate150',
 'ShortDurationEndDate180',
 'ShortDurationPrecipitationValue005',
 'ShortDurationPrecipitationValue010',
 'ShortDurationPrecipitationValue015',
 'ShortDurationPrecipitationValue020',
 'ShortDurationPrecipitationValue030',
 'ShortDurationPrecipitationValue045',
 'ShortDurationPrecipitationValue060',
 'ShortDurationPrecipitationValue080',
 'ShortDurationPrecipitationValue100',
 'ShortDurationPrecipitationValue120',
 'ShortDurationPrecipitationValue150',
 'ShortDurationPrecipitationValue180',
 'Sunrise',
 'Sunset',
 'TStorms',
 'WindEquipmentChangeDate']
 '''
 None

In [15]:
# Let's save merged data into CSV
#merged_data.to_csv("./main_data/merged_data.csv")

In [32]:
# merged_data.shape is (408747, 125)

In [ ]:
# A lot of columns are not needed for our research, such as SOURCE.1 and Backup columns, together with ShortDuration data
# So we are going to discard it manually via Excel
# The average (daily and monthly) also can be discarded, since we have hourly data, thus we can calculate it on the go if needed

# Reason why we change data type manually, is that we need to look into actual values, whereas here, values are still shown as NaN
# But in the excel sheet, they are clearly visible, please see excel image attached.

### Sample images from excel analysis:
![alt text](excel_analysis_sample/column_data_type_adjustment.PNG "Fixing Data Type")
![alt text](excel_analysis_sample/cleaning_extra_strings_in_numbers.PNG "Removing unnecessary strings from numbers")

In [ ]:
# Next we going to work on the NaN values conversion to actual values (set column's data types to their actual type)

In [107]:
# Removed columns:
'''
* Unnamed
* All "Backup..." columns
* All Daily Average
* All Monthly Average
* AWND
* CDSD
* CLDD
* DSNW
* HDSD
* HTDD
* HeavyFog
* TStorms
* WindEquipmentChangeDate
* SOURCE.1
* All "ShortDuration..."
* TStorms
* WindEquipmentChangeDate
* NormalsCoolingDegreeDay
* NormalsHeatingDegreeDay
'''

c:\users\lrspr\anaconda3\envs\weather\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (3,9,15,16,17,18,19,20,21,22,23,24,25,26,27,31,32,33,36,38,39,40,41,42,43,44,46,48,49,51,53,59,61,62,63,64,65,66,72,78,79) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [109]:
# list(merged_data.columns.values)

In [110]:
# print(len(list(weather_df.columns.values)))
# New number of columns is 87

In [121]:
# Columns that we get after removing unnecessary columns
# Let's label expected data type for each

In [128]:
'''
columns_dict = {'STATION':str,
 'DATE':str,
 'REPORT_TYPE':str,
 'SOURCE':str,
 'HourlyAltimeterSetting':float,
 'HourlyDewPointTemperature':int,
 'HourlyDryBulbTemperature':int,
 'HourlyPrecipitation':float,
 'HourlyPresentWeatherType':str,
 'HourlyPressureChange':float,
 'HourlyPressureTendency':float,
 'HourlyRelativeHumidity':float,
 'HourlySeaLevelPressure':float,
 'HourlySkyConditions':str,
 'HourlyStationPressure':float,
 'HourlyVisibility':float,
 'HourlyWetBulbTemperature':int,
 'HourlyWindDirection':str,
 'HourlyWindGustSpeed':float,
 'HourlyWindSpeed':float,
 'REM':str,
 'REPORT_TYPE.1':str,
 'Sunrise':str,
 'Sunset':str}
'''

In [ ]:
# Finally, after setting all data types for all columns using excel, we can now import it into our notebook

In [14]:
# get current directory
curr_dir = os.getcwd()
data_folder = "main_data"
dataset_name = "merged_data_types_defined.csv"
dataset_location = os.path.join(curr_dir, data_folder, dataset_name)

weather_df = pd.read_csv(dataset_location, low_memory=False)

In [15]:
weather_df.head(5)

,STATION,DATE,REPORT_TYPE,SOURCE,HourlyAltimeterSetting,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyPresentWeatherType,HourlyPressureChange,...,HourlyStationPressure,HourlyVisibility,HourlyWetBulbTemperature,HourlyWindDirection,HourlyWindGustSpeed,HourlyWindSpeed,REM,REPORT_TYPE.1,Sunrise,Sunset
0,72406093721,1991-01-01T00:00:00,SAO,C,30.59,13,29,0.00,NaN,NaN,...,30.42,19.88,24,330,NaN,9.0,NaN,SAO,NaN,NaN
1,72406093721,1991-01-01T01:00:00,SAO,3,30.59,13,28,0.00,NaN,-0.02,...,30.42,19.88,24,320,NaN,8.0,AWY015107 20006 46328,SAO,NaN,NaN
2,72406093721,1991-01-01T02:00:00,SAO,3,30.6,15,26,0.00,NaN,NaN,...,30.43,19.88,23,260,NaN,5.0,NaN,SAO,NaN,NaN
3,72406093721,1991-01-01T03:00:00,SAO,3,30.62,16,26,0.00,NaN,NaN,...,30.45,19.88,23,320,NaN,6.0,NaN,SAO,NaN,NaN
4,72406093721,1991-01-01T04:00:00,SAO,3,30.61,16,24,0.00,NaN,-0.02,...,30.44,19.88,22,350,NaN,3.0,AWY003007,SAO,NaN,NaN

In [11]:
weather_df.shape

(408747, 24)

In [17]:
'''
Columns: 
    - Hourly Present Weather Type
    - Hourly Wind Gust Speed
    - Sunrise
    - Sunset
    
They all seem to have a lot of NaN values, so let's check if that's true and if it is, we are going to discard them
'''
None